markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "NetCafe"
markdown: rdiscount

author: "wayne"
atom-baseurl: "http://b.pop925.net"
disqus: "enre"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://foto.com
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

