markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "JoshTime"

author: "JoshTime"
atom-baseurl: "http://hijoe.xyz"
disqus: "enre"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://foto.com
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

